# Generated by Django 4.1.2 on 2022-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='college',
            name='median',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
